In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
rtu = pd.read_csv('RTU.csv')
rtu = rtu.ffill()

In [3]:
pd.Series.unique(rtu['Column3'])

array(['0', 'TIME (0)', 'TIME (1)', '10', '41', '45', '46', '48', '49',
       '47', '18', '40', '42', '43', '17', '29', '15', '16', '44', '31',
       '50', '13', '30', '34', '35', '37', '38', '28', '12', '25', '23',
       '27', '32', '33', '26', '11', '39', '21', '22', '24', '19', '36',
       '14', '51', '64', '20', '60', '59', '52', 'TIME (21)', 'TIME (-19)',
       'TIME (-20)', 'TIME (-21)', 'TIME (22)', 'TIME (23)', 'TIME (-22)',
       '68', '73', '66', '62', '71', '53', '63', '58', '72', 'TIME (-23)',
       'TIME (24)', 'TIME (25)', 'TIME (-24)', 'TIME (26)', 'TIME (-25)',
       '100', '93', '99', '89', '61', 'TIME (-26)', 'TIME (27)',
       'TIME (3601)', '74', '55', '70', '54', 'TIME (-28)', 'TIME (29)',
       'TIME (-27)', 'TIME (28)', '56', 'TIME (30)', 'TIME (-29)',
       'TIME (31)', '90', 'TIME (-30)', '97', '83', 'TIME (-31)',
       'TIME (32)', '65', 'TIME (-32)', 'TIME (33)', '57', 'TIME (-33)',
       'TIME (34)', '81', '86', '91', '75', '82', '67', '96', 'TIME (35)',
       'TIME (-34)', '95', '76', 'TIME (-35)', 'TIME (36)', 'TIME (-36)',
       'TIME (37)', '84', '88', 'TIME (-37)', 'TIME (38)', '92', '98',
       'TIME (-38)', 'TIME (39)', '69', '78', '79', '80', '85', '87', '94',
       'TIME (-39)', 'TIME (40)', 'TIME (-40)', 'TIME (41)', 'TIME (-1)',
       'TIME (-3600)', 'TIME (2)', 'No Data'], dtype=object)

In [4]:
df1 = rtu.copy()

In [5]:
rtu.rename(columns={'Column1': 'Date', 'Column2': 'Time', 'Column3': 'Economiser position %', 'Column4':'DX coil ON?OFF'}, inplace = True)
rtu.rename(columns={'Column5': 'DX coil ON?OFF', 'Column6': 'Supplier Temperature', 'Column7': 'supply fan ON?OFF'}, inplace = True)
rtu.rename(columns={'Column8': 'heating coil ON?OFF', 'Column9': 'Room Temperature'},inplace = True)

In [6]:
rtu.head()

,Date,Time,Economiser position %,DX coil ON?OFF,DX coil ON?OFF,Supplier Temperature,supply fan ON?OFF,heating coil ON?OFF,Room Temperature
0,31-12-2015,00:00:00,0,OFF,OFF,59.5,OFF,OFF,80.1
1,31-12-2015,00:00:00,0,OFF,OFF,60.4,OFF,OFF,80.2
2,31-12-2015,00:15:00,0,OFF,OFF,61,OFF,OFF,80.4
3,31-12-2015,00:30:00,0,OFF,OFF,61.1,OFF,OFF,80.4
4,31-12-2015,00:45:00,0,OFF,OFF,61.2,OFF,OFF,80.4

In [7]:
import matplotlib.pyplot as plt
%matplotlib inline
data = [rtu['Supplier Temperature'], rtu['Room Temperature']]
print list(rtu.columns.values)
#plt.boxplot(data)
#plt.show()
print rtu['Economiser position %'].unique()
print rtu['Supplier Temperature'].unique()
print  rtu['Room Temperature'].unique()

['Date', 'Time', 'Economiser position %', 'DX coil ON?OFF', 'DX coil ON?OFF', 'Supplier Temperature', 'supply fan ON?OFF', 'heating coil ON?OFF', 'Room Temperature']
['0' 'TIME (0)' 'TIME (1)' '10' '41' '45' '46' '48' '49' '47' '18' '40'
 '42' '43' '17' '29' '15' '16' '44' '31' '50' '13' '30' '34' '35' '37' '38'
 '28' '12' '25' '23' '27' '32' '33' '26' '11' '39' '21' '22' '24' '19' '36'
 '14' '51' '64' '20' '60' '59' '52' 'TIME (21)' 'TIME (-19)' 'TIME (-20)'
 'TIME (-21)' 'TIME (22)' 'TIME (23)' 'TIME (-22)' '68' '73' '66' '62' '71'
 '53' '63' '58' '72' 'TIME (-23)' 'TIME (24)' 'TIME (25)' 'TIME (-24)'
 'TIME (26)' 'TIME (-25)' '100' '93' '99' '89' '61' 'TIME (-26)'
 'TIME (27)' 'TIME (3601)' '74' '55' '70' '54' 'TIME (-28)' 'TIME (29)'
 'TIME (-27)' 'TIME (28)' '56' 'TIME (30)' 'TIME (-29)' 'TIME (31)' '90'
 'TIME (-30)' '97' '83' 'TIME (-31)' 'TIME (32)' '65' 'TIME (-32)'
 'TIME (33)' '57' 'TIME (-33)' 'TIME (34)' '81' '86' '91' '75' '82' '67'
 '96' 'TIME (35)' 'TIME (-34)' '95' '76' 'TIME (-35)' 'TIME (36)'
 'TIME (-36)' 'TIME (37)' '84' '88' 'TIME (-37)' 'TIME (38)' '92' '98'
 'TIME (-38)' 'TIME (39)' '69' '78' '79' '80' '85' '87' '94' 'TIME (-39)'
 'TIME (40)' 'TIME (-40)' 'TIME (41)' 'TIME (-1)' 'TIME (-3600)' 'TIME (2)'
 'No Data']
['59.5' '60.4' '61' '61.1' '61.2' '60.9' '61.4' '61.6' '61.3' '61.7' '61.9'
 '60.8' '60.7' '60.3' '60.6' '58' '59.7' '58.6' '58.5' '59.2' '60' '58.8'
 '56.5' '59.8' '62.4' '65.5' '66.5' '64.8' '65.6' '65.8' '67.2' '67.9'
 '68.2' '68.7' '68.6' '68.9' '68.8' '69.6' '69.4' '68.4' '68.3' '65.7'
 '65.1' '64.9' '64' '64.1' '62.7' '57.4' '54.5' '58.4' '60.1' '59.1' '58.1'
 '61.5' '62.1' '56' '53.8' '54.7' '57.8' '55.9' '56.9' '57.2' '53.6'
 'TIME (0)' '54.6' '55.2' '55.8' '54.1' '52.6' '53.9' '51.4' '50.3' '52.2'
 '51.8' '63.3' '65' '65.3' '66.4' '66.7' '66.3' '66.6' '67.1' '67.3' '67'
 '67.4' '67.6' '67.8' '67.5' '68.1' '67.7' '66.1' '61.8' '62.6' '62.3'
 '62.2' '62' '57.7' 'TIME (1)' '56.4' '56.8' '54' '55.3' '57.1' '55.7'
 '60.2' '59.9' '58.9' '57.6' '66.9' '68' '69.7' '69.1' '69.3' '69.2' '69.8'
 '69.5' '70' '70.2' '70.1' '70.3' '70.7' '70.4' '62.9' '64.3' '63.6' '66.2'
 '56.3' '55.1' '59.4' '58.2' '56.6' '56.2' '53.3' '48' '46' '43.3' '45.1'
 '46.8' '45.7' '46.5' '48.3' '48.8' '49.3' '46.9' '48.2' '46.4' '43.6'
 '44.4' '38.4' '40.2' '37.8' '39.7' '41.3' '40.9' '41.8' '40.1' '39.8'
 '42.1' '43' '41.6' '42.2' '40.6' '43.2' '42.9' '43.4' '38.3' '37.2' '38'
 '39.1' '50.5' '57.3' '63.9' '66' '64.7' '64.4' '63' '62.8' '64.2' '64.5'
 '65.4' '65.2' '63.4' '63.5' '59' '54.8' '53.7' '48.6' '48.9' '54.4' '54.3'
 '47.5' '47.9' '48.7' '49.5' '49.9' '49.6' '48.5' '48.4' '51' '53.4' '58.3'
 '55.6' '55' '55.5' '55.4' '46.2' '51.7' '52.3' '51.3' '45.4' '45.5' '45.9'
 '50.8' '44.5' '44.8' '44.7' '45.2' '50.1' '56.7' '51.1' '56.1' '50' '51.2'
 '52.4' '53' '54.2' '59.3' '54.9' '46.7' '47' '48.1' '57.5' '63.2' '58.7'
 '63.1' '62.5' '60.5' '59.6' '63.7' '64.6' '65.9' '52.8' '53.5' '49.8'
 '52.7' '52' '51.5' '43.8' '42.8' '47.4' '52.5' '53.1' '47.1' '44.9' '51.6'
 '50.9' '47.2' '52.1' '49' '42.3' '42.6' '41.7' '41.9' '50.6' '49.2' '45.8'
 '44' '47.6' '45.6' '38.7' '50.2' '49.4' '46.3' '45' '38.9' '44.6' '41.4'
 '47.7' '43.9' '41.5' '46.6' '40' '41.2' '47.3' '50.7' '42' '49.1' '44.1'
 '57' '41' '50.4' '40.7' '43.5' '40.5' '40.4' '45.3' '42.4' '44.2' '47.8'
 '37.5' '38.1' '42.7' '43.7' '57.9' '52.9' '63.8' '49.7' '53.2' '46.1'
 '39.6' '39.5' '38.6' '36.1' '36.3' '38.2' '38.5' '44.3' '37.1' '36.4'
 '36.9' '35.3' '36.5' '38.8' '41.1' '39.4' '40.3' '39.9' '36.6' '37.3'
 '37.4' '43.1' '51.9' '73.6' '73' '72' '71.3' '71.4' '71.5' '71.1'
 'TIME (21)' 'TIME (-19)' 'TIME (-20)' '40.8' '42.5' 'TIME (-21)' '39'
 'TIME (22)' 'TIME (23)' 'TIME (-22)' '70.5' '71.6' '71' '69' '68.5' '70.9'
 'TIME (-23)' 'TIME (24)' '79.8' '72.6' '75.4' '66.8' 'TIME (25)'
 'TIME (-24)' '69.9' '71.8' '70.8' '85.5' '75.9' '73.1' '73.4' '74.1' '74'
 '75' '74.5' '74.4' '73.9' '74.3' '72.8' '72.1' '71.9' 'TIME (26)'
 'TIME (-25)' '71.2' '70.6' '72.9' '72.4' '72.7' '74.2' '74.7' '73.5'
 '75.2' '76.9' '76.5' '75.5' '75.3' '75.6' '75.8' '77.2' '76.4' '74.6'
 '76.1' '76.2' '76.8' '77' '77.1' '77.3' '77.7' '78.4' '78.5' '79.1' '78.7'
 '78.6' '79' '77.9' '78.3' '76.3' '72.5' '71.7' '72.3' '73.3' '72.2' '73.2'
 'TIME (-26)' 'TIME (27)' 'TIME (3601)' 'TIME (-28)' 'TIME (29)'
 'TIME (-27)' 'TIME (28)' '73.8' '74.8' '75.1' '74.9' 'TIME (30)'
 'TIME (-29)' 'TIME (31)' '73.7' '75.7' '76' 'TIME (-30)' 'TIME (-31)'
 'TIME (32)' '80.3' '37.7' '37' '36.7' '36.2' '37.6' 'TIME (-32)'
 'TIME (33)' 'TIME (-33)' 'TIME (34)' 'TIME (35)' 'TIME (-34)' '76.6'
 'TIME (-35)' 'TIME (36)' '76.7' 'TIME (-36)' 'TIME (37)' '79.3'
 'TIME (-37)' 'TIME (38)' 'TIME (-38)' 'TIME (39)' '77.5' '78' '78.1'
 '77.4' 'TIME (-39)' 'TIME (40)' '77.8' '78.9' '78.2' '78.8' 'TIME (-40)'
 'TIME (41)' '79.5' '79.6' '80.2' '79.4' '77.6' '79.2' 'TIME (-1)'
 'TIME (-3600)' 'TIME (2)' 'No Data' '83.7']
['80.1' '80.2' '80.4' '80.5' '80.6' '80.7' '80.8' '80.9' '81' '81.2' '79.6'
 '78.6' '79.1' '79' '78.5' '78.3' '78.1' '77.9' '77.7' '77.6' '77.5' '77.3'
 '77.4' '77.2' '77.1' '77' '76.9' '76.8' '76.6' '76.5' '76.7' 'TIME (0)'
 '76.4' '76.3' '76' '76.1' '75.9' '76.2' '78.9' '79.4' '79.7' '79.8' '79.9'
 '80' '80.3' 'TIME (1)' '81.1' '79.2' '78.8' '78.7' '78.4' '78.2' '78'
 '75.8' '75.7' '75.5' '75.3' '75.2' '75' '75.1' '75.4' '75.6' '74.8' '74.7'
 '74.6' '74.5' '73.9' '72.4' '73.2' '72.8' '72.1' '71.7' '71.4' '74.1'
 '72.9' '73.3' '73.5' '72.2' '72.3' '73.8' '74.2' '74.3' '71.2' '71.6'
 '71.9' '72' '71.8' '72.7' '71.3' '71.5' '74.9' '74.4' '73.6' '73.1' '73'
 '71.1' '74' '73.7' '72.5' '72.6' '73.4' '70.9' '70.5' '70.7' '70.8' '70.1'
 '70.6' '70.3' '71' '69.8' '69.6' '70' '69.9' '68.8' '70.2' '70.4' '79.5'
 '79.3' 'TIME (21)' 'TIME (-19)' 'TIME (-20)' 'TIME (-21)' '69.3'
 'TIME (22)' 'TIME (23)' 'TIME (-22)' '77.8' 'TIME (-23)' 'TIME (24)'
 'TIME (25)' 'TIME (-24)' '81.7' '81.6' '81.8' '82' '81.9' '82.1' '82.2'
 '82.3' '82.4' '81.3' '81.4' 'TIME (26)' 'TIME (-25)' '81.5' '82.5' '82.6'
 '82.8' '82.7' '83' '83.1' '83.2' '83.3' '83.4' '83.5' '83.6' '83.7' '83.8'
 '83.9' '84' '84.1' '84.2' '84.3' '84.4' '84.5' '84.7' '84.9' '85' '85.1'
 '85.2' '85.4' '85.5' '85.3' '85.6' '85.8' '85.9' '86' '85.7' 'TIME (-26)'
 'TIME (27)' 'TIME (3601)' 'TIME (-28)' 'TIME (29)' 'TIME (-27)'
 'TIME (28)' 'TIME (30)' 'TIME (-29)' 'TIME (31)' '82.9' 'TIME (-30)'
 '69.7' '69.5' '69.4' 'TIME (-31)' 'TIME (32)' 'TIME (-32)' 'TIME (33)'
 'TIME (-33)' 'TIME (34)' 'TIME (35)' 'TIME (-34)' '69' '68.5' '69.2'
 'TIME (-35)' 'TIME (36)' 'TIME (-36)' 'TIME (37)' '68.9' '68.7' '68.3'
 '67.9' 'TIME (-37)' 'TIME (38)' 'TIME (-38)' 'TIME (39)' 'TIME (-39)'
 'TIME (40)' 'TIME (-40)' 'TIME (41)' 'TIME (-1)' 'TIME (-3600)' 'TIME (2)'
 'No Data']