In [2]:
import openpyxl
work_order = openpyxl.load_workbook('IIT Work Order Samples (1).xlsm')
print type(work_order)
print work_order.get_sheet_names()
sheet_wo = work_order.get_sheet_by_name('Sheet 1')
print sheet_wo.title

<class 'openpyxl.workbook.workbook.Workbook'>
[u'Sheet 1']
Sheet 1

In [2]:
import pandas as pd
import numpy as np
wo = pd.read_excel('IIT Work Order Samples (1).xlsm')# creating a dataframe from the excel file
wo_fin = pd.read_excel('IIT Work Orders 2015_Present.xls')
wo_des = wo['Description.1'] # considering only the description of the workd orders
wo.fillna('missing')
wo_fin.head()
#wo_it = wo_fin[wo_fin['Building'].str.contains('IT')]
wo_it_des = wo_it['Description']
wo_it['Floor'] = wo_it['Floor'].replace('n/a', np.NaN)

In [3]:
wo_it.Floor.isnull().sum()
wo_count = pd.DataFrame(wo_it['Floor'].value_counts(dropna = False))
wo_count.columns.values

array([u'Floor'], dtype=object)

In [39]:
import numpy as np
import matplotlib.pyplot as plt
#wo_it['Floor'] = wo_it['Floor'].fillna(25)
u, count = np.unique(wo_it['Floor'], return_index = True)
#plt.bar(count, u, align='center',alpha = 0.5)
#df10 = pd.DataFrame({'Floor':u, 'Count': count})
#print df10.sort(['Floor','Count'], ascending=[1,0])
#plt.bar(df10['Floor'],df10['Count'],align='center',alpha = 0.4)
#wo_it['Floor'] = wo_it['Floor'].dropna()
#wo_it.Floor.hist()
#wo_it.Floor.value_counts(dropna =False).hist()
#plt.show()
wo_it.head()

,Wo Number,Description,Assigned To,Building,Floor,Room,Craft,Enter Date,Wo Close Date,Hours SUM
12,WO121611,"[ROOM, IS, TOO, COLD]",TJABCZYN,IT,13,13F3-2,HVAC,2015-01-05 08:52:36,2015-01-06 14:54:47,1.00
19,WO121617,"[CAR, 2, IS, STUCK, ON, 19TH, FLOOR]",MCUSACK1,IT,NaN,n/a,ELEVATOR,2015-01-05 09:57:08,2015-01-30 09:09:12,NaN
29,WO121631,"[ROOM, IS, TOO, COLD]",TJABCZYN,IT,13,13F7-2,HVAC,2015-01-05 10:25:53,2015-01-06 14:55:23,1.50
33,WO121627,"[ROOM, TOO, COLD]",TARIANOU,IT,3,3C7-1,HVAC,2015-01-05 10:43:31,2015-01-05 15:38:34,0.75
39,WO121648,"[REPAIR, TOILET]",TARIANOU,IT,2,WR-02-00,PLUMBING,2015-01-05 11:56:19,2015-01-07 15:33:06,1.25

In [7]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

True

In [56]:
import numpy
from collections import Counter
from nltk.corpus import stopwords
import nltk
result = Counter(" ".join(wo_it['Description'].astype(str)).split(" ")).most_common(220)
df_res = pd.DataFrame(result)
df_res.to_excel('wordfreq.xlsx')
#print df_res[0]
#stop = set(stopwords.words('english'))
#stopwordsfree_words = [word for word in result if word not in stop]
#fd = nltk.FreqDist(wo_it['Description'].astype(str))
#print fd.tabulate()

In [47]:
#wo_it['Description'] = wo_it['Description'].str.split(" ")
import string
wo_it['Description'][62] = wo_it[]
#wo_it['Description'] = wo_it['Description'].translate(None, string.punctuation.translate(None, '"'))
#wo_it['Description'].apply(lambda x:[item for item in x if item not in stop])

SyntaxError: invalid syntax (<ipython-input-47-4d692fa4ee72>, line 3)

In [35]:
s = wo_it.groupby("Floor").Floor.agg(lambda x:len(x.unique()))
pd.value_counts(s).plot(kind="bar")
plt.show()

In [4]:
from collections import Counter
counts = Counter(wo_it_des)
count = counts.most_common()
#for i in xrange(0,14): print counts[i]
#print(count) 
countdf = pd.DataFrame(count)
#print countdf
freq_desc = pd.ExcelWriter('freq_desc_it.xlsx', engine = 'xlsxwriter')
#countdf.to_excel(freq_desc, sheet_name = 'Frequency of Description')
writer = pd.ExcelWriter('iitresearchtower.xlsx', engine = 'xlsxwriter')
df2 = wo_it
df2.to_excel(writer, sheet_name = 'IIT')

In [8]:
def keyword(str):
    df = wo_it[wo_it_des.str.contains(str, na = False)]
    df.to_excel(writer, sheet_name = str)


writer = pd.ExcelWriter('keyword_it.xlsx', engine = 'xlsxwriter')
keyword("HVAC")
keyword("AHU")
keyword("FILTER")
keyword("FAN")
keyword("COIL")
keyword("TOO HOT")
keyword("TOO COLD")
keyword("OVERHEATING")
keyword("HEATING")
keyword("COOLING")
keyword("TEMPERATURE")
keyword("CHILLER")
keyword("BOILER")
keyword("DAMPER")
keyword("STEAM")
keyword("COLD")
keyword("REPAIR")
keyword("BASEMENT")
keyword("SUPPLY")
keyword("FIRE")
keyword("20TH")
keyword("19TH")
keyword("18TH")
keyword("17TH")
keyword("16TH")
keyword("15TH")
keyword("URGENT")
keyword("GOLF")
keyword("2")
keyword("4TH")
keyword("NOISE")
keyword("ROOM")
keyword("BULB")
keyword("LEAKING")
#keyword("A/C")
df = wo_it[wo_it_des.str.contains('A/C', na = False)]
df.to_excel(writer, sheet_name = 'Air_Cond')

In [29]:
wo_it[wo_it_des.str.contains("HVAC", na = False)]
#word_hvac.to_excel(writer, sheet_name = 'HVAC')

,Wo Number,Description,Assigned To,Building,Floor,Room,Craft,Enter Date,Wo Close Date,Hours SUM
2795,WO124409,REPAIR HVAC UNIT,TJABCZYN,IT,11,n/a,MECHANICAL,2015-02-24 10:06:18,2015-02-27 12:50:31,1.0
8823,WO130430,REPAIR HVAC UNIT,TJABCZYN,IT,9,9C5-1,MECHANICAL,2015-06-30 11:48:05,2015-07-13 14:59:25,1.0
12572,WO134195,REPAIR HVAC UNIT-ASAP,MCARMOD1,IT,16,n/a,HVAC EQUIP,2015-09-10 09:28:24,2015-09-11 16:01:31,3.0
15405,WO137035,REPAIR HVAC UNIT - BAD FOR EQUIPMENT,TARIANOU,IT,6,n/a,HVAC EQUIP,2015-10-29 15:34:17,2015-10-30 15:51:17,0.5
21201,WO142836,HVAC SERVICE IN BD4-1,TJABCZYN,IT,0,BD4-1,HVAC EQUIP,2016-02-23 15:24:41,2016-04-25 11:15:07,NaN
24668,WO146303,REPAIR VARIOUS HVAC DUCT WORK - KIRBY,CDEBRIZZ,IT,n/a,n/a,HVAC EQUIP,2016-05-02 12:06:05,2016-05-27 11:07:26,NaN
25406,WO147041,HVAC,TJABCZYN,IT,19,19F8-1,HVAC EQUIP,2016-05-18 09:17:10,2016-05-19 15:03:10,1.0

In [38]:
wo[wo_des.str.contains("AHU", na = False)]
#word_ahu.to_excel(writer, sheet_name = 'AHU')

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
248,WO147137,INCUBATOR - CENTRAL,ER-C,01,n/a,HVAC EQUIP,ORDER FILTERS FOR AHUS IN ERB AND METALS,2016-05-20 11:21:11,"CARMODY, MIKE",JBOOKER2,3.5

In [37]:
 wo[wo_des.str.contains("FILTER", na = False)]
#word_filter.to_excel(writer, sheet_name = 'FILTER')

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
158,WO146604,LIFE SCIENCES RESEARCH - 35 W. 34TH,LR,n/a,n/a,HVAC,REPLACE FAN FILTERS (BI-WEEKLY),2016-05-06 13:49:11,n/a,NOEHMEN,1.25
175,WO146521,KAPPA PHI DELTA - 3330 S. MICHIGAN,KP,3,311,HVAC EQUIP,KPD 311: MOLD IN AIR CONDITIONER/FILTER NEEDS ...,2016-05-06 11:14:37,"ZAMUDIO, LAURENTINA",AMCELLIG,1.02
214,WO146522,KAPPA PHI DELTA - 3330 S. MICHIGAN,KP,2,204,HVAC EQUIP,KPD 204: MOLD IN AIR CONDITIONER/FILTERS NEEDS...,2016-05-06 11:16:17,"ZAMUDIO, LAURENTINA",AMCELLIG,2.00
248,WO147137,INCUBATOR - CENTRAL,ER-C,01,n/a,HVAC EQUIP,ORDER FILTERS FOR AHUS IN ERB AND METALS,2016-05-20 11:21:11,"CARMODY, MIKE",JBOOKER2,3.50
336,WO146836,CROWN HALL - 3360 S. STATE,CR,n/a,n/a,HVAC EQUIP,CROWN HALL CHANGE FILTERS (REF WO142863),2016-05-13 09:19:06,"CARMODY, MIKE",MCARMOD1,1.00
367,WO146845,GALVIN LIBRARY - 35 W. 33RD STREET,GL,1,n/a,HVAC EQUIP,REPLACE FILTERS,2016-05-13 10:01:46,"WORRELL, JENNIFER",AKRAMER1,0.50
467,WO146839,TECH PARK - NORTH - 3410 S. STATE,TN,n/a,n/a,HVAC EQUIP,TECH NORTH CHANGE FILTERS (REF WO142863),2016-05-13 09:24:38,"CARMODY, MIKE",MCARMOD1,1.80

In [36]:
wo[wo_des.str.contains("FAN", na = False)]
#word_fan.to_excel(writer, sheet_name = 'FAN')

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
158,WO146604,LIFE SCIENCES RESEARCH - 35 W. 34TH,LR,n/a,n/a,HVAC,REPLACE FAN FILTERS (BI-WEEKLY),2016-05-06 13:49:11,n/a,NOEHMEN,1.25
249,WO147390,HERMANN HALL - 3241 S. FEDERAL,HH,n/a,n/a,KITCHEN,HH BANQUET SPACE: REPAIR FAN,2016-05-26 11:18:45,"MCMAHON, JOHN",RROJAS1,2.00
409,WO146977,MCCORMICK STUDENT VL. 3241 S WABASH,MS,n/a,n/a,HVAC EQUIP,MSV BOILER ROOM REPAIR EXHAUST FAN,2016-05-17 09:04:49,"STOLLMAYER, JOSEPH",JSTOLLMA,8.00
455,WO147353,INCUBATOR - SOUTH,ER-S,01,n/a,HVAC EQUIP,WORK ON EXAUST FAN FOR RO ROOM ERB( OPEN DAMPERS),2016-05-25 12:48:03,"CARMODY, MIKE",NOEHMEN,8.25
629,WO147081,MCCORM. TRIB. C. C. - 3201 S. STATE,MC,n/a,n/a,OTHER,MC: LOCATE FAN COIL UNITS,2016-05-19 08:52:06,"KIRSHNER, TRACY",TKIRSHNE,3.50
673,WO146473,HERMANN HALL - 3241 S. FEDERAL,HH,1,n/a,HVAC EQUIP,HH REPLACE EXHAUST FAN IN UNISEX BATHROOM,2016-05-05 10:49:39,"MUTH, ROBERT",RMUTH,1.75
678,WO146930,IIT RESEARCH TOWER - 10 W. 35TH,IT,n/a,n/a,PLUMBING,ROD THE FLOOR DRAIN NEAR SUPPLY FAN #8,2016-05-14 07:54:20,"DEBRIZZIO, CHUCK",TARIANOU,8.00
723,WO146605,LIFE SCIENCES RESEARCH - 35 W. 34TH,LR,n/a,n/a,HVAC,REPLACE FAN BELTS,2016-05-06 13:49:23,n/a,MCARMOD1,11.75
880,WO147781,KEATING HALL - 3040 S. WABASH,KH,2,25,MOVES,BIG FAN TO BE MOVED INTO KEATING,2016-06-03 13:10:08,"GILMORE, USHA",FGONZAL1,3.75
886,WO146295,MCCORMICK STUDENT VL. 3241 S WABASH,MS,1,100A,HVAC EQUIP,PM THE FAN COIL,2016-05-02 11:13:10,"MCMAHON, JOHN",SSOLIS,16.00
931,WO147415,INCUBATOR - SOUTH,ER-S,n/a,n/a,ELECTRICAL,WORK ON EXAUST FANS FOR RO ROOM ERB,2016-05-27 09:16:46,"CARMODY, MIKE",DVARGAS4,1.75

In [35]:
wo[wo_des.str.contains("COIL", na = False)]
#word_coil.to_excel(writer, sheet_name = 'COIL')

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
66,WO147070,LIFE SCIENCES - 3105 S. DEARBORN,LS,n/a,n/a,OTHER,LS: REPAIR CHILL WATER COIL,2016-05-18 16:11:57,"NAVA, JAVIER",JNAVA2,3.25
629,WO147081,MCCORM. TRIB. C. C. - 3201 S. STATE,MC,n/a,n/a,OTHER,MC: LOCATE FAN COIL UNITS,2016-05-19 08:52:06,"KIRSHNER, TRACY",TKIRSHNE,3.50
774,WO147413,IIT RESEARCH TOWER - 10 W. 35TH,IT,15,n/a,HVAC EQUIP,CLEAN COILS ON ALL CONVECTORS 15TH FLOOR IIT ...,2016-05-27 09:22:01,"CARMODY, MIKE",NOEHMEN,21.75
886,WO146295,MCCORMICK STUDENT VL. 3241 S WABASH,MS,1,100A,HVAC EQUIP,PM THE FAN COIL,2016-05-02 11:13:10,"MCMAHON, JOHN",SSOLIS,16.00

In [34]:
wo[wo_des.str.contains("TOO HOT", na = False)]
#word_too_hot.to_excel(writer, sheet_name = 'TOO HOT')

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
38,WO147366,SIEGEL HALL - 3301 S. DEARBORN,SH,2,216,HVAC EQUIP,ROOM IS TOO HOT,2016-05-25 14:32:37,"MAUGHAN, LINSEY",AKRAMER1,4.00
183,WO146810,MCCORMICK STUDENT VL. 3241 S WABASH,MS,1,n/a,HVAC EQUIP,OFFICE BY CENTER LOUNGE IN MSV: TOO HOT,2016-05-12 10:59:24,"ZAMUDIO, LAURENTINA",JROGER1,0.75
188,WO146748,LIFE SCIENCES RESEARCH - 35 W. 34TH,LR,2,2C4-2,HVAC EQUIP,ROOM IS TOO HOT - ROOM 2C4-2 - ANIMALS PRESENT,2016-05-11 09:00:08,"MOSSMAN, JANET",DSCOTT4,1.50
211,WO147339,RETTALIATA ENG CTR - 10 WEST 32ND,E1,n/a,n/a,HVAC EQUIP,ROOM IS TOO HOT AGAIN,2016-05-25 10:07:13,"MARTINEZ, DIANA",JNAVA2,0.25
307,WO146754,TECH PARK - SOUTH - 3440 S. STATE,TS,4,4026/4027,HVAC EQUIP,ROOM IS TOO HOT - TECH SOUTH ROOM 4026,2016-05-11 09:19:21,"GODDARD, KRAIG",TARIANOU,0.50
407,WO146271,KAPPA PHI DELTA - 3330 S. MICHIGAN,KP,n/a,n/a,HVAC EQUIP,KPD: TOO HOT - REOPENED - 5/3,2016-05-01 19:57:03,"ZAMUDIO, LAURENTINA",AMCELLIG,2.00
479,WO147288,RETTALIATA ENG CTR - 10 WEST 32ND,E1,n/a,n/a,HVAC EQUIP,ROOM IS TOO HOT,2016-05-24 11:12:20,"MARTINEZ, DIANA",JNAVA2,0.50
515,WO147276,PERLSTEIN HALL - 10 W. 33RD,PH,n/a,n/a,HVAC EQUIP,URGENT--PH-214A LAB IS ALMOST 90F/ROOM IS TOO HOT,2016-05-24 09:32:42,"HALE, DONNA",RMUTH,2.50
516,WO147286,VANDERCOOK - 3140 S. FEDERAL,VA,1,104,HVAC EQUIP,ROOM IS TOO HOT - COMPUTER ROOM - URGENT,2016-05-24 11:07:40,"LOPEZ, STEPHANIE",RMUTH,1.50
739,WO147332,TECH PARK - SOUTH - 3440 S. STATE,TS,2,2035,HVAC EQUIP,ROOM IS TOO HOT,2016-05-25 09:09:52,MENEMENCI GINGERY,TARIANOU,0.75
759,WO147139,INCUBATOR - SOUTH,ER-S,02,220S-1,HVAC EQUIP,ROOM IS TOO HOT,2016-05-20 11:43:44,"BARNES, HALEY",JBOOKER2,1.00
816,WO147299,PERLSTEIN HALL - 10 W. 33RD,PH,n/a,n/a,HVAC EQUIP,PH-217A OFFICE/ROOM IS TOO HOT,2016-05-24 12:18:13,"HALE, DONNA",RMUTH,1.00
819,WO147307,RETTALIATA ENG CTR - 10 WEST 32ND,E1,1,111A,HVAC EQUIP,ROOM IS TOO HOT,2016-05-24 14:05:48,"COLLINS, GLADYS",JNAVA2,0.50
858,WO147377,SIEGEL HALL - 3301 S. DEARBORN,SH,3,308C,HVAC EQUIP,SH 308C: ROOM TOO HOT,2016-05-26 08:21:52,"GARZA, VALERIA",AKRAMER1,0.50
891,WO147138,INCUBATOR - SOUTH,ER-S,02,220S,HVAC EQUIP,URGENT ROOM IS TOO HOT - OVERHEATING,2016-05-20 11:34:02,"BARNES, HALEY",JBOOKER2,1.00
947,WO147284,IIT RESEARCH TOWER - 10 W. 35TH,IT,16,n/a,HVAC EQUIP,ROOM IS TOO HOT-URGENT,2016-05-24 10:58:55,"MURPHY, MARGARET",TARIANOU,0.10
952,WO147085,LIFE SCIENCES - 3105 S. DEARBORN,LS,1,146D,HVAC EQUIP,ROOM IS TOO HOT,2016-05-19 09:46:29,"KAPLAN, DANIEL",JNAVA2,0.50
974,WO147712,ALUMNI HALL - 3201 S. DEARBORN,AM,2,202,HVAC EQUIP,ROOM IS TOO HOT,2016-06-01 15:49:47,"GOODLOE, LESLIE",WPALM,1.00

In [33]:
wo[wo_des.str.contains("TOO COLD", na = False)]
#word_too_cold.to_excel(writer, sheet_name = 'TOO COLD')

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
41,WO147628,INCUBATOR - SOUTH,ER-S,02,220S,HVAC EQUIP,ROOM IS TOO COLD,2016-05-31 11:07:46,"BARNES, HALEY",JBOOKER2,4.00
93,WO147609,LIFE SCIENCES - 3105 S. DEARBORN,LS,1,160,HVAC EQUIP,ROOM IS TOO COLD,2016-05-31 08:34:31,"PANOSYAN, ZABEL",JNAVA2,0.75
184,WO146947,IIT RESEARCH TOWER - 10 W. 35TH,IT,8,n/a,HVAC EQUIP,ROOM IS TOO COLD - OTS - TOWER 8TH FLOOR,2016-05-16 10:36:00,"GODDARD, KRAIG",DBROOKS4,0.50
223,WO146662,LIFE SCIENCES - 3105 S. DEARBORN,LS,1,146D,HVAC EQUIP,ROOM IS TOO COLD,2016-05-09 10:06:27,"KAPLAN, DANIEL",WPALM,0.75
305,WO146731,IIT RESEARCH TOWER - 10 W. 35TH,IT,8,n/a,HVAC EQUIP,ROOM IS TOO COLD - OTS - TOWER 8TH FLOOR,2016-05-10 15:04:57,"GODDARD, KRAIG",DBROOKS4,1.00
317,WO147013,TECH PARK - SOUTH - 3440 S. STATE,TS,4,4041,HVAC EQUIP,ROOM IS TOO COLD,2016-05-17 13:40:19,"GASTON, KEVA",TARIANOU,0.25
344,WO147011,LIFE SCIENCES RESEARCH - 35 W. 34TH,LR,0,BB12-1,HVAC EQUIP,PRIMATE AREAS TOO COLD - URGENT - BASEMENT FAC...,2016-05-17 13:25:45,"MOSSMAN, JANET",DSCOTT4,0.10
362,WO147002,PERLSTEIN HALL - 10 W. 33RD,PH,n/a,n/a,HVAC EQUIP,PH-127C OFFICE/ROOM IS TOO COLD,2016-05-17 12:11:40,"HALE, DONNA",RMUTH,0.50
465,WO146940,IIT RESEARCH TOWER - 10 W. 35TH,IT,17,n/a,HVAC EQUIP,ROOM IS TOO COLD,2016-05-16 09:09:59,"MITCHELL, MARCIA",TJABCZYN,1.00
526,WO147718,STUART BUILDING - 10 W. 31ST STREET,SB,0,n/a,HVAC EQUIP,ROOM IS TOO COLD,2016-06-02 09:16:50,"MCBROOM, ANN",WPALM,0.75
550,WO146275,FARR HALL - 3300 S. MICHIGAN,FH,n/a,n/a,HVAC EQUIP,ROOM IS TOO COLD,2016-05-02 07:54:14,WITTLEDER,TKIRSHNE,0.75
569,WO146723,IIT RESEARCH TOWER - 10 W. 35TH,IT,17,n/a,HVAC EQUIP,ROOM IS TOO COLD,2016-05-10 13:18:08,"MITCHELL, MARCIA",TJABCZYN,0.50
619,WO147302,INCUBATOR - SOUTH,ER-S,01,126S,HVAC EQUIP,INCUBATOR SOUTH - 126S - ROOM IS TOO COLD,2016-05-24 13:06:54,"BARNES, HALEY",JBOOKER2,3.50
670,WO146678,LIFE SCIENCES RESEARCH - 35 W. 34TH,LR,1,1A4-1,HVAC EQUIP,ROOM IS TOO COLD-URGENT - ENTIRE 1ST FLOOR AREA,2016-05-09 12:19:51,"MACK, JULIE",JBOOKER2,3.50
684,WO147040,TECH PARK - SOUTH - 3440 S. STATE,TS,2,2005,HVAC EQUIP,TECH SOUTH ROOM 2005 IS TOO COLD SINCE MONDAY ...,2016-05-18 09:11:37,"HAMMOND, CELIA",TARIANOU,0.25
685,WO147005,TECH PARK - SOUTH - 3440 S. STATE,TS,4,n/a,HVAC EQUIP,ROOM IS TOO COLD,2016-05-17 12:26:08,"SIEGEL, JOSHUA",TARIANOU,0.25
757,WO147089,TECH PARK - SOUTH - 3440 S. STATE,TS,4,4B8-2,HVAC EQUIP,ROOM IS TOO COLD,2016-05-19 10:33:14,"HOUSER, PAMELA",TARIANOU,0.75

In [32]:
wo[wo_des.str.contains("OVERHEATING", na = False)]
#word_overheating.to_excel(writer, sheet_name = 'OVERHEATING')

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
891,WO147138,INCUBATOR - SOUTH,ER-S,02,220S,HVAC EQUIP,URGENT ROOM IS TOO HOT - OVERHEATING,2016-05-20 11:34:02,"BARNES, HALEY",JBOOKER2,1.0

In [31]:
wo[wo_des.str.contains("HEATING", na = False)]
#word_heating.to_excel(writer, sheet_name = 'HEATING')

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
276,WO146279,GRADUATE HALL - 70 E. 33RD,GH,1,119,PLUMBING,GH GROUND FLOOR: MEN'S BATHROOM HS NOT HEATING,2016-05-02 08:46:53,"ZAMUDIO, LAURENTINA",SSOLIS,1.75
325,WO147316,MCCORM. TRIB. C. C. - 3201 S. STATE,MC,n/a,n/a,OTHER,SHUT OFF PERIMETER HEATING MTCC,2016-05-24 15:13:13,"GARZA, VALERIA",TKIRSHNE,1.75
891,WO147138,INCUBATOR - SOUTH,ER-S,02,220S,HVAC EQUIP,URGENT ROOM IS TOO HOT - OVERHEATING,2016-05-20 11:34:02,"BARNES, HALEY",JBOOKER2,1.00
971,WO147065,COMMONS - 3200 S. WABASH,CO,n/a,n/a,KITCHEN,"COMMONS SOUTH POD: REPAIR FOOD WARMER, NOT HEA...",2016-05-18 14:28:37,"MCMAHON, JOHN",RROJAS1,2.00

In [61]:
wo[wo_des.str.contains("COOLING", na = False)]

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
1,WO146383,PERLSTEIN HALL - 10 W. 33RD,PH,2,206,HVAC EQUIP,OPEN COOLING VENT,2016-05-03 15:33:05,"MARTIN, ROXANNE",RMUTH,1.50
67,WO147208,CARMEN HALL - 60 EAST 32ND,CH,3,303,HVAC EQUIP,CH 303: HOSES FROM COOLING UNITS ARE DETACHED ...,2016-05-20 12:25:09,"ZAMUDIO, LAURENTINA",FWATSON,0.50
166,WO147219,MCCORM. TRIB. C. C. - 3201 S. STATE,MC,n/a,n/a,HVAC EQUIP,MTCC CHANGE OVER TO COOLING,2016-05-23 08:47:31,"STOLLMAYER, JOSEPH",JSTOLLMA,1.00
191,WO147335,MAIN CAMPUS/ACADEMIC GROUNDS,GROUNDS,n/a,n/a,HVAC EQUIP,SHOW JAVIER HOW TO USE COOLING TOWER GOODWA...,2016-05-25 09:48:33,"CARMODY, MIKE",NOEHMEN,3.75
291,WO147266,COMMONS - 3200 S. WABASH,CO,n/a,n/a,KITCHEN,COMMONS NORTH POD: SINGLE DOOR VICTORY COOLER ...,2016-05-24 08:57:25,"MCMAHON, JOHN",RROJAS1,4.50
417,WO147221,MCCORMICK STUDENT VL. 3241 S WABASH,MS,n/a,n/a,HVAC EQUIP,MSV CHANGE OVER TO COOLING,2016-05-23 08:49:03,"STOLLMAYER, JOSEPH",JSTOLLMA,4.00
501,WO146354,MCCORM. TRIB. C. C. - 3201 S. STATE,MC,n/a,n/a,HVAC EQUIP,MTCC BLEED AIR IN COOLING TOWER,2016-05-03 11:46:24,"KIRSHNER, TRACY",TKIRSHNE,0.75
630,WO147692,COMMONS - 3200 S. WABASH,CO,n/a,n/a,KITCHEN,COMMONS SOUTH POD REPAIR PREP TABLE - NOT COOLING,2016-06-01 13:15:22,SODEXO DINING,RROJAS1,4.50
727,WO147334,MACHINERY HALL - 100 WEST 33RD,MH,1,n/a,HVAC EQUIP,MH CARPENTER SHOP A/C NOT COOLING,2016-05-25 10:00:06,"WILLIAMS, GREGORY",AKRAMER1,4.75
863,WO147298,RETTALIATA ENG CTR - 10 WEST 32ND,E1,n/a,n/a,HVAC EQUIP,E1 CLEAN STRAINERS & COOLING TOWER,2016-05-24 12:23:23,"NAVA, JAVIER",JNAVA2,16.00
877,WO147595,SOUTH HALL - 71 E. 32ND,SO,4,417,HVAC EQUIP,SO 417: AC ISN'T COOLING.,2016-05-27 14:56:35,"ZAMUDIO, LAURENTINA",AMCELLIG,1.00
897,WO147635,NORTH HALL - 71 EAST 32ND,NH,1,103,KITCHEN,NH 103: FRIDGE IS NOT COOLING.LIGHT INSIDE TUR...,2016-05-31 10:25:09,"ZAMUDIO, LAURENTINA",AMCELLIG,2.00

In [62]:
wo[wo_des.str.contains("TEMPERATURE", na = False)]

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
575,WO146782,COMMONS - 3200 S. WABASH,CO,n/a,n/a,HVAC EQUIP,"COMMONS: ADJUST TEMPERATURE, REALLY WARM",2016-05-12 08:15:26,"GARZA, VALERIA",TKIRSHNE,0.25

In [63]:
wo[wo_des.str.contains("CHILLER", na = False)]

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
34,WO146739,LIFE SCIENCE RESEARCH CHILLER,LR-CHILLER,01,n/a,CUSTODIAL,CLEAN UP IN CHILLER SHACK ASAP,2016-05-11 07:43:06,"CARMODY, MIKE",NOEHMEN,16.25
235,WO146315,LIFE SCIENCE RESEARCH CHILLER,LR-CHILLER,n/a,n/a,HVAC EQUIP,CLEAN SEPERATOR IN LSR CHILLER SHACK DAILY,2016-05-02 13:08:29,"CARMODY, MIKE",TARIANOU,12.25
260,WO147607,IIT RESEARCH TOWER - 10 W. 35TH,IT,20,20F5-1,HVAC EQUIP,TAKE CHILLER READINGS IN IIT TOWER DAILY,2016-05-31 08:32:45,"CARMODY, MIKE",TARIANOU,1.50
372,WO146317,LIFE SCIENCE RESEARCH CHILLER,LR-CHILLER,n/a,n/a,HVAC EQUIP,TAKE CHILLER READINGS DAILY FOR MONTH OF MAY 2016,2016-05-02 13:20:44,"CARMODY, MIKE",DSCOTT4,3.75
848,WO146316,LIFE SCIENCE RESEARCH CHILLER,LR-CHILLER,n/a,n/a,HVAC EQUIP,TAKE CHEMICAL TESTS DAILY TOWER AND LSR CHILL...,2016-05-02 13:14:03,"CARMODY, MIKE",TARIANOU,25.25
893,WO147766,MATERIALS TECH.- 3350 S. FEDERAL,MT,n/a,n/a,HVAC EQUIP,REPAIR INFAC CHILLER (ANCHOR ),2016-06-03 09:48:27,"CARMODY, MIKE",CDEBRIZZ,2.00

In [68]:
wo[wo_des.str.contains("BOILER", na = False)]

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
120,WO146570,MCCORMICK STUDENT VL. 3241 S WABASH,MS,n/a,n/a,MECHANICAL,BOILER INSPECTIONS,2016-05-06 13:43:39,n/a,MKING8,9.50
332,WO146890,MCCORMICK STUDENT VL. 3241 S WABASH,MS,n/a,n/a,MECHANICAL,BOILER INSPECTIONS,2016-05-13 14:04:21,n/a,MKING8,3.75
409,WO146977,MCCORMICK STUDENT VL. 3241 S WABASH,MS,n/a,n/a,HVAC EQUIP,MSV BOILER ROOM REPAIR EXHAUST FAN,2016-05-17 09:04:49,"STOLLMAYER, JOSEPH",JSTOLLMA,8.00
530,WO147516,MCCORMICK STUDENT VL. 3241 S WABASH,MS,n/a,n/a,MECHANICAL,BOILER INSPECTIONS,2016-05-27 14:20:30,n/a,MKING8,3.00
820,WO147168,MCCORMICK STUDENT VL. 3241 S WABASH,MS,n/a,n/a,MECHANICAL,BOILER INSPECTIONS,2016-05-20 13:15:31,n/a,MKING8,1.00
961,WO147836,MCCORMICK STUDENT VL. 3241 S WABASH,MS,n/a,n/a,MECHANICAL,BOILER INSPECTIONS,2016-06-06 09:31:16,n/a,MKING8,1.50

In [69]:
wo[wo_des.str.contains("DAMPER", na = False)]

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
79,WO147230,LIFE SCIENCES RESEARCH - 35 W. 34TH,LR,n/a,n/a,HVAC EQUIP,"CHECK BELTS AND DAMPER ACTUATORS ON LEF-2A, 2B",2016-05-23 10:13:08,"GAUGER, JAMES",DSCOTT4,1.50
386,WO146988,HERMANN HALL - 3241 S. FEDERAL,HH,n/a,n/a,HVAC EQUIP,HH REPAIR MIXED DAMPERS,2016-05-17 10:34:27,"MUTH, ROBERT",RMUTH,4.75
455,WO147353,INCUBATOR - SOUTH,ER-S,01,n/a,HVAC EQUIP,WORK ON EXAUST FAN FOR RO ROOM ERB( OPEN DAMPERS),2016-05-25 12:48:03,"CARMODY, MIKE",NOEHMEN,8.25
592,WO147234,LIFE SCIENCES RESEARCH - 35 W. 34TH,LR,n/a,n/a,HVAC EQUIP,"CHECK BELTS AND DAMPER ACTUATORS ON LEF 2A,2B ...",2016-05-23 10:46:49,"CARMODY, MIKE",DSCOTT4,1.50

In [70]:
wo[wo_des.str.contains("STEAM", na = False)]

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
406,WO146278,GUNSAULUS - 3140 S. MICHIGAN,GU,9,902,HVAC EQUIP,902 STEAM LEAK,2016-05-02 08:52:37,"MCMAHON, JOHN",JROGER1,3.75
822,WO147403,COMMONS - 3200 S. WABASH,CO,0,n/a,OTHER,LEAKING WATER IN COMMONS NEAR THE STEAM TABLE,2016-05-26 15:13:10,SODEXO DINING,RROJAS1,0.75
851,WO146365,GUNSAULUS - 3140 S. MICHIGAN,GU,9,902,HVAC EQUIP,GUNS ROOM 902 STEAM LEAK - WEEKEND CALL IN ON ...,2016-05-03 13:24:05,"DEBRIZZIO, CHUCK",TKIRSHNE,4.25

In [49]:
wo[wo_des.str.contains("EXHAUST", na = False)]

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
409,WO146977,MCCORMICK STUDENT VL. 3241 S WABASH,MS,n/a,n/a,HVAC EQUIP,MSV BOILER ROOM REPAIR EXHAUST FAN,2016-05-17 09:04:49,"STOLLMAYER, JOSEPH",JSTOLLMA,8.00
673,WO146473,HERMANN HALL - 3241 S. FEDERAL,HH,1,n/a,HVAC EQUIP,HH REPLACE EXHAUST FAN IN UNISEX BATHROOM,2016-05-05 10:49:39,"MUTH, ROBERT",RMUTH,1.75
730,WO147740,HERMANN HALL - 3241 S. FEDERAL,HH,n/a,n/a,HVAC EQUIP,REPAIR WIRING FOR HH KITCHEN EXHAUST,2016-06-02 13:15:50,"CUSACK, MATT",RMUTH,38.50

In [6]:
wo[wo_des.str.contains("VAB", na = False)]

Empty DataFrame
Columns: [WO Number, Description, Building, Floor, Room, Craft, Description.1, Enter Date, Requestor, Assigned To, Labor]
Index: []

In [9]:
wo[wo_des.str.contains("NOISE", na = False)]

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
164,WO147265,CARMEN HALL - 60 EAST 32ND,CH,5,504,HVAC EQUIP,CH 504: AC MAKES TOO MUCH NOISE,2016-05-24 08:34:35,"ZAMUDIO, LAURENTINA",FWATSON,1.0
772,WO147650,IIT RESEARCH TOWER - 10 W. 35TH,IT,20,n/a,HVAC EQUIP,20TH FLOOR TOWER - MECHANICAL NOISE,2016-05-31 13:54:32,"SIEGEL, JOSHUA",TJABCZYN,5.0
872,WO147031,STATE STREET VILLAGE - NORTH BLDG,SN,4,NN-4.5,PLUMBING,SSV NORTH N 4.5:TOILET MAKES NOISE AND TAKES L...,2016-05-17 22:03:25,"ZAMUDIO, LAURENTINA",MKING8,1.0

In [10]:
wo[wo_des.str.contains("A/C", na = False)]

,WO Number,Description,Building,Floor,Room,Craft,Description.1,Enter Date,Requestor,Assigned To,Labor
246,WO147633,SIEGEL HALL - 3301 S. DEARBORN,SH,3,309,HVAC EQUIP,SH ROOM 309 A/C NOT WORKING & NEEDED FOR COMPU...,2016-05-31 12:05:30,"HERMLE, EILEEN",AKRAMER1,0.50
396,WO147645,SIEGEL HALL - 3301 S. DEARBORN,SH,n/a,n/a,ELECTRICAL,CHECK ELECTRIC FOR COMPUTER LAB A/C IN SIEGEL ...,2016-05-31 12:28:36,"CUSACK, MATT",EMENDOZ2,5.00
705,WO147672,SIEGEL HALL - 3301 S. DEARBORN,SH,n/a,n/a,HVAC EQUIP,(AMI) RENT PORTABLE A/C UNITS FOR SH COMPUTER ...,2016-06-01 09:54:16,"CUSACK, MATT",MCUSACK1,1.00
727,WO147334,MACHINERY HALL - 100 WEST 33RD,MH,1,n/a,HVAC EQUIP,MH CARPENTER SHOP A/C NOT COOLING,2016-05-25 10:00:06,"WILLIAMS, GREGORY",AKRAMER1,4.75
949,WO147329,PERLSTEIN HALL - 10 W. 33RD,PH,2,212,HVAC EQUIP,PH 212: NO A/C - NEEDS A/C,2016-05-25 09:23:33,"GARZA, VALERIA",RMUTH,2.25

In [60]:
wo_it[wo_it_des.str.contains('LOUD', na = False)]

,Wo Number,Description,Assigned To,Building,Floor,Room,Craft,Enter Date,Wo Close Date,Hours SUM
9024,WO130632,A/C FAN SUPER LOUD AT 2C8-1,TARIANOU,IT,2,2C8-1,HVAC,2015-07-06 12:05:27,2015-07-07 14:09:03,2.25
10723,WO132342,LIGHT FIXTURE SHAKING LOUDLY-URGENT,ECHO,IT,19,n/a,ELECTRICAL,2015-08-11 17:00:58,2015-08-12 15:59:58,2.00
11731,WO133351,A/C FAN SUPER LOUD AT 2C8-1-REOPEN AGAIN 10.13.15,TARIANOU,IT,2,2C8-1,HVAC EQUIP,2015-08-27 11:59:38,2015-10-20 14:28:39,0.60
15821,WO137454,ROOM VENTS/BLOWERS TOO LOUD,TJABCZYN,IT,1,n/a,HVAC EQUIP,2015-11-06 07:48:43,2015-11-17 14:47:48,1.00
19880,WO141515,LOUD MACHINE SOUND ABOVE TOWER 19TH FLOOR - WE...,TARIANOU,IT,19,n/a,NaN,2016-01-29 10:59:58,2016-01-29 15:58:41,1.00

In [63]:
wo_it[wo_it_des.str.contains('RATTL', na = False)]

Empty DataFrame
Columns: [Wo Number, Description, Assigned To, Building, Floor, Room, Craft, Enter Date, Wo Close Date, Hours SUM]
Index: []